{% set name = "django-tables2" %}
{% set version = "3.0.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jieter/django-tables2/archive/v{{ version }}.tar.gz
  sha256: cf39a68df4a688e805e91b0aaf0470dc2ec8806d04a2b39a67331ad39870d501

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - django >=4.2

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - python -c "import django; from django.conf import settings; settings.configure(); django.setup(); import django_tables2;"

about:
  home: https://github.com/jieter/django-tables2
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: django-tables2 simplifies the task of turning sets of data into HTML tables.
  doc_url: https://django-tables2.readthedocs.io/en/latest/
  dev_url: https://github.com/jieter/django-tables2

extra:
  recipe-maintainers:
    - gscoppino
    - miguelgomezgomez
